# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entrees'},
        ),
    ]
