# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20170515_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='topic3333',
        ),
    ]
