# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20170516_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Kyle'},
        ),
    ]
